# Generated by Django 4.2.5 on 2024-10-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$gLfmOVpSgEajthcOAkYd1K$r321cXq9Q5XuHbQuIXrGyvOxoySuEhhPam+Pay9rE90=', max_length=128),
        ),
    ]
