# Generated by Django 4.2.5 on 2024-10-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$2fpls4XBouaRENNV2CIXde$5Q1EkbvvSBq+/LhreLORzsJjhB84RSrjOfpLT1u2P6Y=', max_length=128),
        ),
    ]
