# Generated by Django 4.2.5 on 2024-10-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_parent', to='students.student', to_field='studentID'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$NvNpXqN4OeBO1TArEDOgLc$amVZoc9+n9JoQwXVDdlQ6cHt6r/2TARkVmtRhvNEAxk=', max_length=128),
        ),
    ]
