# Generated by Django 4.2.5 on 2024-10-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_session_parent_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qjau0szovEu371U1kcutWt$p8sDo02IEUnsJ9xROuZiwoiQPTGTt4do3lzs8CsILcM=', max_length=128),
        ),
    ]
