# Generated by Django 4.2.5 on 2024-10-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_staff_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('semester_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jvakyh0sTJP1vldPss32vx$81vkaFPyK1NDVmZjALSc/sryFjg+mpqBU2NEnIo0afA=', max_length=128),
        ),
    ]
