# Generated by Django 4.2.5 on 2024-10-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_staff_password_staffactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$tnXTU4zkkz2fimUnCrscCP$KewKfWC8xRAMmcDaoihRlZPSyOoQxkx6UuQ3avgbGjc=', max_length=128),
        ),
    ]
