# Generated by Django 4.2.5 on 2024-10-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_activitylog_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$hJuzyfbOOoBnBGYL6gLu7q$baI/mNhXvpclHQMzV75mtaZYBcpABuW1f6pA8qXwgdc=', max_length=128),
        ),
    ]
