# Generated by Django 4.2.5 on 2024-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_session_semester_name_session_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$9NzfPfO63nkZQSJZY0omoZ$SeMbYwoQm7OvH36xPJRAtmSJxaO1JwGZ8Cc7fPchaB8=', max_length=128),
        ),
    ]
