# Generated by Django 4.2.5 on 2024-11-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_transaction_amount_alter_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='semester_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$uQNox05bdRzWm3aat2uQxa$IWt4E6CDP3/tosuwzyAkxmrjZuuA8uoENyypmvnnznc=', max_length=128),
        ),
    ]
