# Generated by Django 4.2.5 on 2024-10-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ps8x1BUAFjLtW4eXCHY8Ta$FcXbbVygHQCrylkOOlghHbcA84S5uTr5FxvMqKq7AAM=', max_length=128),
        ),
    ]
