# Generated by Django 4.2.5 on 2024-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$lYJN2iC7mOOoVo4FGrGi00$UoO+EYvufMArkgzJOJMoPsaynn9sR7n7lWIeAEnfBTY=', max_length=128),
        ),
    ]
