# Generated by Django 4.2.5 on 2024-10-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ZDeHPPP1NBBtsXMg9JrALc$l/2cWuxNdqBHbrtS4NJlomr+q4bdpNWC6OdPopm0amo=', max_length=128),
        ),
    ]
