# Generated by Django 4.2.5 on 2024-10-28 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$skoEYhxVjyLGLlV0BbYMEL$U7dUt1AU9ZKZSw17nMvgTUdqaRWX3lHaCOSoDi0fgS8=', max_length=128),
        ),
    ]
