# Generated by Django 4.2.5 on 2024-10-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_activitylog_timestamp_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$nhSdgGk1BpjqYTpfSmlwFL$Hh4jH6khE6/PW+zbQqsGF+DHosSfuoulStmbWXlQoeU=', max_length=128),
        ),
    ]
