# Generated by Django 4.2.5 on 2024-11-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_transaction_semester_name_transaction_year_and_more'),
        ('students', '0015_alter_staff_password'),
    ]

    operations = [
    ]
