# Generated by Django 5.1.4 on 2024-12-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$RMCVNuqu4tDezo48yUPMi1$IBZRoBooKqo728eOjded8yEVNt/7UC8DPbl1QFCTlMs=', max_length=128),
        ),
    ]
